# Permalinks
permalink:        pretty

# Setup
url:              http://bk2dcradle.github.io

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:          /blog

title:            Convoluted Ramblings

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
    A type ISTP programmer @BITS Pilani

# The tags listed as entries in the sidebar
sidebar_tags:     [vim, git, algorithms]

# Fallback image and color if not overwritten for tag or post
image:            http://qwtel.com/hydejack/public/img/nap.jpg
color:            '#A85641'

author:
  name:           'Ankit Sultana'
  twitter:        AnkitSultana
  github:         bk2dcradle
  photo:          # http://qwtel.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
      A sophomore at BITS Pilani, a programmer on the web
