# User Settings | Edit there as per required

title: ankit sultana
url: "http://ankitsultana.me"
baseurl: "/blog"

# This will show up at the top of index page
site_heading: >
    ankit <span class="faded">'s blog</span>

email: ankitsultana@gmail.com
author: Ankit Sultana
# This description will show up in google search results
# (for index page) etc.
description: >
    A sophomore at BITS Pilani, a programmer on the web.

# This will what will show against &copy; in the footer
copyright: ankit
# Toggle your short bio, which will displayed on your index page
# Just toggle it and run jekyll again to see
intro: false
# This will be displayed in your intro
short_bio: >
    Welcome! This is <span>accent</span>, a mobile friendly theme for Jekyll. The main feature of this
    theme, apart from being minimal is that you can change the accent color. Refer the
    <a class="underline different-highlight" href="http://ankitsultana.me/accent/documentation.html">
        Documentation
    </a>
    to know how.

permalink: /:title.html

# Comments are powered by disqus
comments: true

# keep about_stub roughly 12 words long for best results
# This will show up at the bottom of each post
# Note that about_footer should be true if you want
# to see author information at the bottom of each post
about_stub: >
    A sophomore at BITS Pilani, a programmer on the web.

about_footer: true

twitter_username: AnkitSultana
github_username: bk2dcradle
facebook_id: ankitsultana10

favicon: true
favicon_location: "images/favicon.ico"

profile_picture: images/temp.png
paginate: 5
paginate_path: "/page/:num"
tracking_id: UA-69243698-2

# Facebook Stuff
og_image: "includes/og_image.jpg" # This will show in facebook thumbnails

####################################
####################################
####################################
### Build Settings | Don't Touch ###
####################################
####################################
####################################

markdown: kramdown

gems:
    - jekyll-paginate

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"
